name: update-issues
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run update-issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
